version: 2.1
orbs:
  newman: postman/newman@0.0.2
jobs:
  newman-collection-run:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          collection: ./apitest/CircleCI-Postman-Base.postman_collection.json
workflows:
  main:
    jobs:
      - newman-collection-run

      #helloworld